# Site settings
title: Shadaj's Blog
url: "http://blog.shadaj.me" # the base hostname & protocol for your site
twitter_username: ShadajL

# Build settings
plugins: [jekyll-paginate]

comments: true

disqus_shortname: shadajsblog

main_site: http://shadaj.me

name: Shadaj Laddad

avatar: /profile.jpg

paginate: 5
